# This is nginx config running outside of docker


# Frontend: barishm.com & www.barishm.com
server {
    server_name barishm.com www.barishm.com;

    root /home/barish/robobg/web/dist;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    # Optional: cache static assets
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        expires 1M;
        add_header Cache-Control "public";
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/barishm.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/barishm.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}

# Backend API: api.barishm.com
server {
    server_name api.barishm.com;

    # Reverse proxy to backend service (example: running on localhost:8080)
    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Serve static files for /images
    location /files/ {
        alias /home/barish/robobg/files/;
        autoindex off;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/barishm.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/barishm.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = www.barishm.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = barishm.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name barishm.com www.barishm.com;
    return 404; # managed by Certbot




}
server {
    if ($host = api.barishm.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name api.barishm.com;
    return 404; # managed by Certbot


}
