import { useSelector } from 'react-redux';

const SpecsRenderer = ({ textKey }) => {
    const lang = useSelector((state) => state.language.lang);

    const Str = {
        en: {
            brand:"Brand",
            model:"Model",
            image:"Image",
            mapping: "Mapping",
            mappingSensorType:"Mapping Sensor Type",
            highPrecisionMap: "High Precision Map",
            frontCamera: "Front Camera",
            rechargeResume : "Recharge Resume",
            autoDockAndRecharge : "Auto Dock And Recharge",
            noiseLevel:"Noise Level",
            display: "Display",
            sideBrushes:"Side Brushes",
            voicePrompts: "Voice Prompts",
            suctionPower:"Suction Power",
            cleaningArea:"Cleaning Area",
            dustbinCapacity:"Dustbin Capacity",
            disposableDustBagCapacity:"Disposal Dustbag Capacity",
            autoDirtDisposal: "Auto Dirt Disposal",
            barrierCrossHeight:"Barrier Cross Height",
            hepaFilter:"Hepa Filter",
            washableFilter:"Washable Filter",
            wetMopping:"Wet Mopping",
            electricWaterFlowControl:"Electric Water Flow Control",
            waterTankCapacity:"Water Tank Capacity",
            vibratingMoppingPad:"Vibrating Mopping Pad",
            autoMopLifting:"Auto Mop Lifting",
            autoWaterTankRefilling:"Auto Water Tank Refilling",
            autoMopWashing: "Auto Mop Washing",
            batteryCapacity:"Battery Capacity",
            batteryLife:"Battery Life",
            chargingTime:"Charging Time",
            ratedPower:"Rated Power",
            scheduling:"Scheduling",
            irRfRemoteControl:"Ir Rf Remote Control",
            wifiSmartphoneApp:"Wifi Smartphone App",
            wifiFrequencyBand:"Wifi Frequency Band",
            amazonAlexaSupport:"Amazon Alexa Support",
            googleAssistantSupport:"Google Assistant Support",
            magneticVirtualWalls:"Virtual Walls",
            realTimeTracking:"Real Time Tracking",
            digitalBlockedAreas:"Digital Blocked Areas",
            zonedCleaning:"Zoned Cleaning",
            multiFloorMaps:"Multi Floor Maps",
            manualMovementControl:"Manual Movement Control",
            selectedRoomCleaning:"Selected Room Cleaning",
            noMopZones:"No Mop Zones",
            carpetBoost:"Carpet Boost",
            cliffSensor:"Cliff Sensor",
            dirtSensor:"Dirt Sensor",
            fullDustbinSensor:"Full Dustbin Sensor",
            weight:"Wight",
            width:"Width",
            height:"Height",
            inTheBox: "In The Box",
            releaseDate: "Release Date",

            brandDesc:"Brand",
            modelDesc:"Model",
            imageDesc:"Image",
            mappingDesc: "A technology that can be based on a camera sensor, Laser Direct Structuring (LDS) laser or a gyroscope. The robot scans out a room and creates a map. The robots with mapping provide better performance by building the most efficient path of cleaning without missing a spot",
            mappingSensorTypeDesc:"There are different types of mapping technologies such as LDS based, camera based, and gyroscope/accelerometer based mapping. Some robot vacuums use combined technologies.",
            highPrecisionMapDesc: "A high-precision map means that it is at least 98% accurate and corresponds to your real home layout",
            frontCameraDesc: "The robot equipped with a front camera and can see, recognize, and avoid objects on its way.",
            rechargeResumeDesc: "If the robot can't finish a job on one charge, it automatically returns to the charging dock. Resuming intends the robot to continue cleaning from the same place it left off after it's done charging. This feature is perfect for big households, when the robot is not able to clean the entire house on one charge",
            autoDockAndRechargeDesc: "When the robot vacuum finishes the job or runs low on battery, it automatically returns to the dock to recharge",
            noiseLevelDesc:"Note, some robot cleaners have a few power settings, in this field, we specify a noise level claimed by the manufacturer, in lowest power mode.",
            displayDesc: "The robot have a display that shows additional information such as battery level, errors, scheduling time, or cleaning status",
            sideBrushesDesc:"How many side brushes the robot comes equipped with. Side brushes help to reach corners and edges channeling all the dust and dirt to the main central brush where it gets sucked up right into the dustbin",
            voicePromptsDesc: "The robot uses voice prompts to inform you about the current status of the robot vacuum whether it is charging, cleaning, etc.",
            suctionPowerDesc:"The higher the suction power, the better it performs on carpeted surface removing dust and smaller debris. A high suction power robot vacuum cleaner is more effective in getting rid of dirt hidden away in your carpets",
            cleaningAreaDesc:"How much of a cleaning area the robot covers during one cleaning cycle",
            dustbinCapacityDesc:"The dustbin size matters if you have pets or a big house.",
            disposableDustBagCapacityDesc:"The capacity of the disposable dust bag from the auto-emptying base",
            autoDirtDisposalDesc: "The robot vacuum has a special dock that automatically empties the robot's dustbin when it is docked",
            barrierCrossHeightDesc:"The height of an obstacle/carpet/threshold the robot can climb.",
            hepaFilterDesc:"HEPA is an acronym that stands for High-Efficiency Particulate Air. The HEPA filter is a type of mechanical air filter; it works by forcing air through a fine mesh that traps harmful particles such as pollen, pet dander, dust mites, and tobacco smoke. A robot vacuum with HEPA filtration is safer for allergy and asthma sufferers",
            washableFilterDesc:"This type of filter can be washed, so you don't need to replace it as often.",
            wetMoppingDesc:"The robot can do mopping and sweeping. Most of the 2-in-1 cleaners come with a water tank and a mop cloth, a few models have a single mop cloth only",
            electricWaterFlowControlDesc:"An electric water pump inside the robot controls the water output depending on your needs. You can change the water output mode in the app",
            waterTankCapacityDesc:"The more water the water tank holds, the more significant cleaning area it covers before gets dry",
            vibratingMoppingPadDesc:"The mopping pad of the robot vibrates which helps to get rid of stains from the floor",
            autoMopLiftingDesc:"Ability to automatically lift the mopping pad when a carpet is detected, so you can mop hard floors and vacuum carpets in a single clean",
            autoWaterTankRefillingDesc:"The robot supports a base that refills the water tank inside the robot with water after or during mopping.",
            autoMopWashingDesc: "The robot washes automatically the mop during or after mopping",
            batteryCapacityDesc:"A larger battery provides a longer running time on one charge.",
            batteryLifeDesc:"How much time the robot can work before needs to recharge",
            chargingTimeDesc:"How much time the robot needs to recharge",
            ratedPowerDesc:"Rated power is the max power the machine can deliver under normal circumstances",
            schedulingDesc:"The feature allows setting the robot to start cleaning automatically at a specific time",
            irRfRemoteControlDesc:"The IR remote control helps to manage the robot's movements, schedule it to work, start, stop, etc",
            wifiSmartphoneAppDesc:"The robot supports Wi-Fi and has a smartphone app; it can be controlled even when you are not at home",
            wifiFrequencyBandDesc:"Some robot vacuums work only with 2.4 GHz wi-fi band, others can also work in 5 GHz wi-fi network",
            amazonAlexaSupportDesc:"The robot is compatible with Alexa-enabled devices, and can be controlled by voice commands",
            googleAssistantSupportDesc:"The robot works with Google Home so it can be controlled via simple voice commands",
            magneticVirtualWallsDesc:"A physical wall barrier can be two types: magnetic tape and a block. They both work the same way by keeping the robot out of the areas you don't want to be cleaned",
            realTimeTrackingDesc:"Ability to watch in real-time where the robot is located on the map of your house and where it has already cleaned",
            digitalBlockedAreasDesc:"It means the app supports creating restricted areas the robot can not cross when is vacuuming. Helpful when you don't want the robot to go to certain places",
            zonedCleaningDesc:"You can make the robot clean within a particular area by setting a zone inside the app",
            multiFloorMapsDesc:"The robot stores more than one map in memory. This feature is useful for people who live in a house with more than one level",
            manualMovementControlDesc:"With this feature, the robot vacuum can be controlled like a radio car through the app",
            selectedRoomCleaningDesc:"This option allows the robot vacuum to clean a specific room (or a few rooms) by selecting this room in the app.",
            noMopZonesDesc:"You can set virtual no-mop zones in the app to restrict the robot from going to certain places (for example with carpets) and it will avoid these areas in mopping mode",
            carpetBoostDesc:"Thanks to this feature, the robot increases suction power to maximum once its sensors recognize the carpeted surface. It helps to save battery life",
            cliffSensorDesc:"Cliff sensors prevent the robot from falling from stairs",
            dirtSensorDesc:"The dirt detect feature helps the robot to provide more thoughtful cleaning by recognizing the dirtiest areas",
            fullDustbinSensorDesc:"The robot has a sensor that detects when the dustbin is full and sends a notification to the user.",
            weightDesc:"The total weight of the robot vacuum",
            widthDesc:"It refers to the robot's diameter (for round shaped robot vacuums) or width. Smaller diameter helps the robot to reach narrow places",
            heightDesc:"If you want to use the robot vacuum under your bed or furniture, check the gap between the floor and furniture and ensure the robot vacuum will fit under it.",
            inTheBoxDesc: "What kind of accessories the package contents",
            releaseDateDesc: "The date when the robot vacuum was released to the market",
        },
        bg: {
            brand:"Brand",
            model:"Model",
            image:"Image",
            mapping: "Картографиране",
            mappingSensorType:"Тип сензор за картографиране",
            highPrecisionMap: "Карта с висока точност",
            frontCamera: "Предна камера",
            rechargeResume : "Презареждане и възобновяване",
            autoDockAndRecharge : "Автоматично докинг устройство и презареждане",
            noiseLevel:"Ниво на шум",
            display: "Дисплей",
            sideBrushes:"Странични четки",
            voicePrompts: "Гласови указания",
            suctionPower:"Всмукателна мощност",
            cleaningArea:"Зона за почистване",
            dustbinCapacity:"Капацитет на кофата за боклук",
            disposableDustBagCapacity:"Капацитет на торбата за прах",
            autoDirtDisposal: "Автоматично изхвърляне на мръсотия",
            barrierCrossHeight:"Височина на преградата",
            hepaFilter:"Хепа филтър",
            washableFilter:"Миещ се филтър",
            wetMopping:"Мокро почистване",
            electricWaterFlowControl:"Електрически контрол на водния поток",
            waterTankCapacity:"Капацитет на резервоара за вода",
            vibratingMoppingPad:"Вибрираща подложка за почистване",
            autoMopLifting:"Автоматично повдигане на моп",
            autoWaterTankRefilling:"Автоматично зареждане на резервоар за вода",
            autoMopWashing: "Автоматично пране с моп",
            batteryCapacity:"Капацитет на батерията",
            batteryLife:"Живот на батерията",
            chargingTime:"Време за зареждане",
            ratedPower:"Оценена сила",
            scheduling:"Планиране",
            irRfRemoteControl:"Ir Rf дистанционно управление",
            wifiSmartphoneApp:"Wifi приложение за смартфон",
            wifiFrequencyBand:"Wifi честотна лента",
            amazonAlexaSupport:"Поддръжка на Amazon Alexa",
            googleAssistantSupport:"Поддръжка на Google Assistant",
            magneticVirtualWalls:"Магнитни виртуални стени",
            realTimeTracking:"Проследяване в реално време",
            digitalBlockedAreas:"Цифрови блокирани зони",
            zonedCleaning:"Зонално почистване",
            multiFloorMaps:"Многоетажни карти",
            manualMovementControl:"Ръчен контрол на движението",
            selectedRoomCleaning:"Почистване на избрани стаи",
            noMopZones:"Без моп зони",
            carpetBoost:"Carpet Boost",
            cliffSensor:"Сензор за скала",
            dirtSensor:"Сензор за мръсотия",
            fullDustbinSensor:"Пълен сензор за боклук",
            weight:"Тегло",
            width:"Ширина",
            height:"Височина",
            inTheBox: "В кутията",
            releaseDate: "Дата на излизане",

            brandDesc:"Brand",
            modelDesc:"Model",
            imageDesc:"Image",
            mappingDesc: "A technology that can be based on a camera sensor, Laser Direct Structuring (LDS) laser or a gyroscope. The robot scans out a room and creates a map. The robots with mapping provide better performance by building the most efficient path of cleaning without missing a spot",
            mappingSensorTypeDesc:"There are different types of mapping technologies such as LDS based, camera based, and gyroscope/accelerometer based mapping. Some robot vacuums use combined technologies.",
            highPrecisionMapDesc: "A high-precision map means that it is at least 98% accurate and corresponds to your real home layout",
            frontCameraDesc: "The robot equipped with a front camera and can see, recognize, and avoid objects on its way.",
            rechargeResumeDesc: "If the robot can't finish a job on one charge, it automatically returns to the charging dock. Resuming intends the robot to continue cleaning from the same place it left off after it's done charging. This feature is perfect for big households, when the robot is not able to clean the entire house on one charge",
            autoDockAndRechargeDesc: "When the robot vacuum finishes the job or runs low on battery, it automatically returns to the dock to recharge",
            noiseLevelDesc:"Note, some robot cleaners have a few power settings, in this field, we specify a noise level claimed by the manufacturer, in lowest power mode.",
            displayDesc: "The robot have a display that shows additional information such as battery level, errors, scheduling time, or cleaning status",
            sideBrushesDesc:"How many side brushes the robot comes equipped with. Side brushes help to reach corners and edges channeling all the dust and dirt to the main central brush where it gets sucked up right into the dustbin",
            voicePromptsDesc: "The robot uses voice prompts to inform you about the current status of the robot vacuum whether it is charging, cleaning, etc.",
            suctionPowerDesc:"The higher the suction power, the better it performs on carpeted surface removing dust and smaller debris. A high suction power robot vacuum cleaner is more effective in getting rid of dirt hidden away in your carpets",
            cleaningAreaDesc:"How much of a cleaning area the robot covers during one cleaning cycle",
            dustbinCapacityDesc:"The dustbin size matters if you have pets or a big house.",
            disposableDustBagCapacityDesc:"The capacity of the disposable dust bag from the auto-emptying base",
            autoDirtDisposalDesc: "The robot vacuum has a special dock that automatically empties the robot's dustbin when it is docked",
            barrierCrossHeightDesc:"The height of an obstacle/carpet/threshold the robot can climb.",
            hepaFilterDesc:"HEPA is an acronym that stands for High-Efficiency Particulate Air. The HEPA filter is a type of mechanical air filter; it works by forcing air through a fine mesh that traps harmful particles such as pollen, pet dander, dust mites, and tobacco smoke. A robot vacuum with HEPA filtration is safer for allergy and asthma sufferers",
            washableFilterDesc:"This type of filter can be washed, so you don't need to replace it as often.",
            wetMoppingDesc:"The robot can do mopping and sweeping. Most of the 2-in-1 cleaners come with a water tank and a mop cloth, a few models have a single mop cloth only",
            electricWaterFlowControlDesc:"An electric water pump inside the robot controls the water output depending on your needs. You can change the water output mode in the app",
            waterTankCapacityDesc:"The more water the water tank holds, the more significant cleaning area it covers before gets dry",
            vibratingMoppingPadDesc:"The mopping pad of the robot vibrates which helps to get rid of stains from the floor",
            autoMopLiftingDesc:"Ability to automatically lift the mopping pad when a carpet is detected, so you can mop hard floors and vacuum carpets in a single clean",
            autoWaterTankRefillingDesc:"The robot supports a base that refills the water tank inside the robot with water after or during mopping.",
            autoMopWashingDesc: "The robot washes automatically the mop during or after mopping",
            batteryCapacityDesc:"A larger battery provides a longer running time on one charge.",
            batteryLifeDesc:"How much time the robot can work before needs to recharge",
            chargingTimeDesc:"How much time the robot needs to recharge",
            ratedPowerDesc:"Rated power is the max power the machine can deliver under normal circumstances",
            schedulingDesc:"The feature allows setting the robot to start cleaning automatically at a specific time",
            irRfRemoteControlDesc:"The IR remote control helps to manage the robot's movements, schedule it to work, start, stop, etc",
            wifiSmartphoneAppDesc:"The robot supports Wi-Fi and has a smartphone app; it can be controlled even when you are not at home",
            wifiFrequencyBandDesc:"Some robot vacuums work only with 2.4 GHz wi-fi band, others can also work in 5 GHz wi-fi network",
            amazonAlexaSupportDesc:"The robot is compatible with Alexa-enabled devices, and can be controlled by voice commands",
            googleAssistantSupportDesc:"The robot works with Google Home so it can be controlled via simple voice commands",
            magneticVirtualWallsDesc:"A physical wall barrier can be two types: magnetic tape and a block. They both work the same way by keeping the robot out of the areas you don't want to be cleaned",
            realTimeTrackingDesc:"Ability to watch in real-time where the robot is located on the map of your house and where it has already cleaned",
            digitalBlockedAreasDesc:"It means the app supports creating restricted areas the robot can not cross when is vacuuming. Helpful when you don't want the robot to go to certain places",
            zonedCleaningDesc:"You can make the robot clean within a particular area by setting a zone inside the app",
            multiFloorMapsDesc:"The robot stores more than one map in memory. This feature is useful for people who live in a house with more than one level",
            manualMovementControlDesc:"With this feature, the robot vacuum can be controlled like a radio car through the app",
            selectedRoomCleaningDesc:"This option allows the robot vacuum to clean a specific room (or a few rooms) by selecting this room in the app.",
            noMopZonesDesc:"You can set virtual no-mop zones in the app to restrict the robot from going to certain places (for example with carpets) and it will avoid these areas in mopping mode",
            carpetBoostDesc:"Thanks to this feature, the robot increases suction power to maximum once its sensors recognize the carpeted surface. It helps to save battery life",
            cliffSensorDesc:"Cliff sensors prevent the robot from falling from stairs",
            dirtSensorDesc:"The dirt detect feature helps the robot to provide more thoughtful cleaning by recognizing the dirtiest areas",
            fullDustbinSensorDesc:"The robot has a sensor that detects when the dustbin is full and sends a notification to the user.",
            weightDesc:"The total weight of the robot vacuum",
            widthDesc:"It refers to the robot's diameter (for round shaped robot vacuums) or width. Smaller diameter helps the robot to reach narrow places",
            heightDesc:"If you want to use the robot vacuum under your bed or furniture, check the gap between the floor and furniture and ensure the robot vacuum will fit under it.",
            inTheBoxDesc: "What kind of accessories the package contents",
            releaseDateDesc: "The date when the robot vacuum was released to the market",
        }
    }
    const text = Str[lang][textKey];


    return text;
}
export default SpecsRenderer;